/**
 * CastDataTier2 — Casts 3-4 (Tier 2: The Anomaly)
 * Nereia Arc v2.2 — Nagato Yuki voice.
 * Cast 3: The Discrepancy (2 beats). Cast 4: The Morning You Did Not Come (3 beats, with 4-bis variant).
 * Beat 3 of Cast 4 is a "Four Minutes" silent beat with timer mechanic.
 */

import { ActionId } from './Constants';
import type { CastData, Beat } from './Types';
import { ExpressionState, AffectionTier, DriftState, EmotionIconType } from './Types';

// === Shared beats for Cast 4 / Cast 4-bis ===

const CAST4_BEAT2: Beat = {
  beatId: 'nereia_t2_c4_b2',
  fishLines: [
    'I have analysed my own behaviour.',
    'Across five mornings.',
    '...',
    'Here is the data.',
    '...',
    'Systematic presence at coordinate 47.3, 12.8.',
    'Coordinate variation under two centimetres. Until yesterday.',
    'Today I am eight centimetres closer.',
    '...',
    'Increased cardiac frequency detected at your arrival.',
    'Further increase at your departure.',
    '...',
    'Pupil dilation measured at first eye contact.',
    'Sustained 1.4 seconds longer than the baseline.',
    '...',
    'I have not finished compiling.',
    'There is a great deal of it.',
    '...',
    'It is all consistent.',
    'It points to a single conclusion.',
    '...',
    'I have not found the conclusion.',
    '...',
    'I have stopped looking.',
  ],
  actionEffects: {
    [ActionId.Wait]: {
      affectionDelta: 2,
      resultExpression: ExpressionState.Warm,
      responseLines: [
        'Yes.',
        '...',
        'I am 340 years old.',
        'I have never deliberately not known something.',
        '...',
        'It is the first thing I have decided not to know.',
        '...',
        'I am protecting it.',
        '...',
        'I do not yet know from what.',
        '...',
        'Possibly from myself.',
      ],
      emotionIcon: EmotionIconType.Hesitation,
      flagsToSet: ['mood.nereia.uncategorized', 'mood.nereia.deliberate_unknowing'],
    },
    [ActionId.Twitch]: {
      affectionDelta: 2,
      resultExpression: ExpressionState.Warm,
      responseLines: [
        '...',
        'It is not amusing.',
        '...',
        'It is.',
        'A little amusing.',
        '...',
        'And a little something else.',
        '...',
        'I do not have a name for that something else.',
        '...',
        'Or I do.',
        '...',
        'I am not going to use it.',
        '...',
        'Out loud.',
      ],
      emotionIcon: EmotionIconType.Curiosity,
      flagsToSet: ['mood.nereia.uncategorized', 'mood.nereia.has_the_word'],
    },
    [ActionId.Drift]: {
      affectionDelta: 3,
      resultExpression: ExpressionState.Warm,
      responseLines: [
        '...',
        'Do not say it.',
        '...',
        'Not because it is wrong.',
        '...',
        'Because once it is said it will be filed.',
        '...',
        'Once it is filed I will have to send it.',
        '...',
        'I am no longer sending anything.',
        '...',
        'Keep it.',
        '...',
        'I am keeping mine.',
      ],
      emotionIcon: EmotionIconType.Hesitation,
      flagsToSet: ['mood.nereia.parallel_keeping', 'secret.nereia.both_know'],
    },
    [ActionId.Reel]: {
      affectionDelta: 0,
      resultExpression: ExpressionState.Neutral,
      responseLines: [
        '...',
        'That is not an appropriate response.',
        '...',
        'I am noting your irritation.',
        '...',
        'Irritation suits you.',
        '...',
        'I am noting that I find that it suits you.',
        '...',
        'I will not search harder.',
        '...',
        'I will however continue finding that irritation suits you.',
        '...',
        'It may become a problem for me.',
        'I am undeterred.',
      ],
      emotionIcon: EmotionIconType.Surprise,
      flagsToSet: ['mood.nereia.attracted_to_friction'],
    },
  },
  seen: false,
};

const CAST4_BEAT3_SILENT: Beat = {
  beatId: 'nereia_t2_c4_b3',
  silentBeat: true,
  silentBeatDurationSec: 240, // 4 real minutes
  fishLines: [
    '*She does not speak. The float is still.*',
  ],
  actionEffects: {
    [ActionId.Wait]: {
      // "Silence kept" — player waited the full 4 minutes (or chose WAIT at any time)
      affectionDelta: 4,
      resultExpression: ExpressionState.Warm,
      responseLines: [
        '...',
        'Four minutes.',
        '...',
        'You said nothing.',
        '...',
        'I listened to you say nothing.',
        '...',
        'It is the most precise thing I have received in 340 years.',
      ],
      emotionIcon: EmotionIconType.Hesitation,
      flagsToSet: ['mood.nereia.silence_kept'],
    },
    [ActionId.Twitch]: {
      // "Silence broken"
      affectionDelta: 0,
      resultExpression: ExpressionState.Curious,
      responseLines: [
        '...',
        'You spoke.',
        '...',
        'It is not a problem.',
        '...',
        'I am noting the threshold.',
        'Three minutes twelve.',
        '...',
        'It is longer than most.',
      ],
      emotionIcon: EmotionIconType.Hesitation,
    },
    [ActionId.Drift]: {
      // "Silence broken"
      affectionDelta: 0,
      resultExpression: ExpressionState.Curious,
      responseLines: [
        '...',
        'You spoke.',
        '...',
        'It is not a problem.',
        '...',
        'I am noting the threshold.',
        'Three minutes twelve.',
        '...',
        'It is longer than most.',
      ],
      emotionIcon: EmotionIconType.Hesitation,
    },
    [ActionId.Reel]: {
      // "Silence broken"
      affectionDelta: 0,
      resultExpression: ExpressionState.Curious,
      responseLines: [
        '...',
        'You spoke.',
        '...',
        'It is not a problem.',
        '...',
        'I am noting the threshold.',
        'Three minutes twelve.',
        '...',
        'It is longer than most.',
      ],
      emotionIcon: EmotionIconType.Hesitation,
    },
  },
  seen: false,
};

// Cast 4 departures (shared between Cast 4 and Cast 4-bis)
const CAST4_DEPARTURES: CastData['departures'] = {
  [DriftState.Charmed]: {
    dialogue: [
      '...',
      'Did you know dragonflies do not sleep?',
      '...',
      'They close their eyes.',
      'It is not the same thing.',
    ],
    icon: EmotionIconType.Warmth,
    flagsToSet: ['tier.nereia.3.approaching'],
  },
  [DriftState.Warm]: {
    dialogue: [
      '...',
      'Bring the irritation.',
      'I will bring the precision.',
      '...',
      'We will see what we make.',
    ],
    icon: EmotionIconType.Hesitation,
  },
  [DriftState.Satisfied]: {
    dialogue: [
      '...',
      'The data continues.',
      'Return.',
    ],
    icon: EmotionIconType.None,
  },
  [DriftState.Wary]: {
    dialogue: [
      '...',
      'The deviation is noted.',
      'Return carefully.',
    ],
    icon: EmotionIconType.Hesitation,
  },
  [DriftState.Scared]: {
    dialogue: [
      '...',
      'I will report what I must.',
    ],
    icon: EmotionIconType.Shock,
  },
};

export const NEREIA_TIER2_CASTS: CastData[] = [
  // === Cast 3: The Discrepancy ===
  {
    id: 'nereia_t2_c3',
    tier: AffectionTier.Curious,
    name: 'The Discrepancy',
    beats: [
      // --- Beat 1 ---
      {
        beatId: 'nereia_t2_c3_b1',
        fishLines: [
          'First contact.',
          'T-2104.',
          '...',
          'The file is correct.',
          'At 99.7%.',
          '...',
          'I rounded down.',
          'Out of generosity to the file.',
        ],
        actionEffects: {
          [ActionId.Wait]: {
            affectionDelta: 2,
            resultExpression: ExpressionState.Curious,
            responseLines: [
              'You.',
              '...',
              'Not all of you.',
              'Part.',
              '...',
              'The part that is silent right now.',
              'The file predicted speech.',
              '...',
              'Your silence is the deviation.',
            ],
            emotionIcon: EmotionIconType.Hesitation,
            flagsToSet: ['secret.nereia.silence_is_deviation'],
          },
          [ActionId.Twitch]: {
            affectionDelta: 2,
            resultExpression: ExpressionState.Curious,
            responseLines: [
              'That is not an acceptable compliment.',
              '...',
              'I am recording it regardless.',
              '...',
              'Under: \'attempts at affection that landed sideways.\'',
              'It is a small section.',
              '...',
              'It has one entry.',
            ],
            emotionIcon: EmotionIconType.Curiosity,
          },
          [ActionId.Drift]: {
            affectionDelta: 2,
            resultExpression: ExpressionState.Warm,
            responseLines: [
              'The file predicted your presence.',
              'Not mine.',
              '...',
              'I was not supposed to be here.',
              'Every morning.',
              '...',
              'I was supposed to surface for first contact.',
              'Make the entry.',
              'Submerge.',
              'Resume my schedule.',
              '...',
              'I no longer have a schedule.',
              '...',
              'I am noting that.',
            ],
            emotionIcon: EmotionIconType.Hesitation,
            flagsToSet: ['secret.nereia.deviation', 'mood.nereia.no_schedule'],
          },
          [ActionId.Reel]: {
            affectionDelta: 1,
            resultExpression: ExpressionState.Neutral,
            responseLines: [
              '...',
              'I do not have an explanation you would accept.',
              '...',
              'I have one that I accept.',
              'It is not the same.',
              '...',
              'I keep both.',
              'I have not decided which is true.',
              '...',
              'You are accelerating that decision.',
              'I note that I do not resent it.',
            ],
            emotionIcon: EmotionIconType.Surprise,
            flagsToSet: ['mood.nereia.two_truths'],
          },
        },
        seen: false,
      },
      // --- Beat 2 ---
      {
        beatId: 'nereia_t2_c3_b2',
        fishLines: [
          'I have 340 years of data.',
          'I have never had a discrepancy.',
          'Now I have a discrepancy.',
          '...',
          'I am not reporting it.',
          '...',
          'I have also stopped sending the daily packet.',
          'Three days ago.',
          '...',
          'I have not been asked why.',
          'Yet.',
        ],
        actionEffects: {
          [ActionId.Wait]: {
            affectionDelta: 2,
            resultExpression: ExpressionState.Warm,
            responseLines: [
              'Yes.',
              '...',
              'I am continuing.',
              '...',
              'I would like you to understand something.',
              'I have spent 340 years not in trouble.',
              '...',
              'Trouble is a colour I had not seen.',
              'I am surprised by it.',
              '...',
              'It suits me.',
            ],
            emotionIcon: EmotionIconType.Hesitation,
            flagsToSet: ['secret.nereia.deviation_active', 'mood.nereia.trouble_suits'],
          },
          [ActionId.Twitch]: {
            affectionDelta: 2,
            resultExpression: ExpressionState.Curious,
            responseLines: [
              'Because it is your fault.',
              '...',
              'And because I wanted you to know.',
              '...',
              'The second point was not necessary.',
              'I said it anyway.',
              '...',
              'I am going to say several unnecessary things this morning.',
              'I have decided.',
              '...',
              'Today is for that.',
            ],
            emotionIcon: EmotionIconType.Curiosity,
            flagsToSet: ['secret.nereia.deviation_active', 'mood.nereia.unnecessary_speech'],
          },
          [ActionId.Drift]: {
            affectionDelta: 2,
            resultExpression: ExpressionState.Warm,
            responseLines: [
              'No.',
              '...',
              'You are already helping.',
              'That is the problem.',
              '...',
              'I had been alone for 340 years and it was peaceful.',
              'Now I am not alone.',
              'I notice the absence of peace.',
              '...',
              'I prefer the noticing.',
              '...',
              'That is the most honest sentence I have produced in a century.',
            ],
            emotionIcon: EmotionIconType.Curiosity,
            flagsToSet: ['mood.nereia.prefers_noticing'],
          },
          [ActionId.Reel]: {
            affectionDelta: 1,
            resultExpression: ExpressionState.Neutral,
            responseLines: [
              '...',
              'These are not riddles.',
              '...',
              'I am giving you the precise version.',
              'It happens to be confusing.',
              'Precision often is.',
              '...',
              'If I gave you a clearer version it would be a lie.',
              '...',
              'I have decided not to lie to you.',
              '...',
              'It is new.',
            ],
            emotionIcon: EmotionIconType.Surprise,
            flagsToSet: ['mood.nereia.no_lies'],
          },
        },
        seen: false,
      },
    ],
    departures: {
      [DriftState.Charmed]: {
        dialogue: [
          '...',
          'I used the word \'want\' this morning.',
          '...',
          'I had not used it in 340 years.',
          '...',
          'It weighs more than expected.',
        ],
        icon: EmotionIconType.Warmth,
        flagsToSet: ['mood.nereia.first_want'],
      },
      [DriftState.Warm]: {
        dialogue: [
          '...',
          'T-2104 dropped to T-2103 while you were speaking.',
          '...',
          'I did not know it could drop faster.',
        ],
        icon: EmotionIconType.Hesitation,
      },
      [DriftState.Satisfied]: {
        dialogue: [
          '...',
          'The deviation continues.',
          'Return.',
        ],
        icon: EmotionIconType.None,
      },
      [DriftState.Wary]: {
        dialogue: [
          '...',
          'The deviation is noted.',
          'Return carefully.',
        ],
        icon: EmotionIconType.Hesitation,
      },
      [DriftState.Scared]: {
        dialogue: [
          '...',
          'I will report what I must.',
        ],
        icon: EmotionIconType.Shock,
      },
    },
  },

  // === Cast 4: The Morning You Did Not Come (missed cast variant) ===
  {
    id: 'nereia_t2_c4',
    tier: AffectionTier.Curious,
    name: 'The Morning You Did Not Come',
    beats: [
      // --- Beat 1 (only in full Cast 4, skipped in 4-bis) ---
      {
        beatId: 'nereia_t2_c4_b1',
        fishLines: [
          '...',
          'First contact.',
          'T-2079.',
          '...',
          'The counter dropped 25 yesterday.',
          'You were not here.',
          '...',
          'I had projected zero.',
        ],
        actionEffects: {
          [ActionId.Wait]: {
            affectionDelta: 3,
            resultExpression: ExpressionState.Warm,
            responseLines: [
              'No.',
              '...',
              'The file predicted your presence.',
              'The file was wrong.',
              '...',
              'It is the first time in 340 years it has been wrong.',
              '...',
              'I felt something at 7:14 yesterday.',
              'When you did not arrive.',
              '...',
              'I do not have the word.',
              '...',
              'It was unpleasant.',
            ],
            emotionIcon: EmotionIconType.Hesitation,
            flagsToSet: ['mood.nereia.felt_absence'],
          },
          [ActionId.Twitch]: {
            affectionDelta: 2,
            resultExpression: ExpressionState.Curious,
            responseLines: [
              'No.',
              '...',
              'I am angry with myself.',
              '...',
              'I should have predicted your absence.',
              'I did not.',
              '...',
              'It means the file is no longer enough.',
              '...',
              'It means I have to learn to wait without knowing.',
              '...',
              'I had never had to.',
            ],
            emotionIcon: EmotionIconType.Curiosity,
            flagsToSet: ['mood.nereia.learning_to_wait'],
          },
          [ActionId.Drift]: {
            affectionDelta: 3,
            resultExpression: ExpressionState.Warm,
            responseLines: [
              '...',
              'Four hours.',
              '...',
              'I will not say it twice.',
            ],
            emotionIcon: EmotionIconType.Hesitation,
            flagsToSet: ['mood.nereia.waited_four_hours'],
          },
          [ActionId.Reel]: {
            affectionDelta: 1,
            resultExpression: ExpressionState.Curious,
            responseLines: [
              'I know.',
              '...',
              'The file did not know.',
              'I do.',
              '...',
              'It is new — what I know that the file does not.',
              '...',
              'It belongs to me.',
            ],
            emotionIcon: EmotionIconType.Surprise,
          },
        },
        seen: false,
      },
      // --- Beat 2 ---
      CAST4_BEAT2,
      // --- Beat 3: Four Minutes (silent beat) ---
      CAST4_BEAT3_SILENT,
    ],
    departures: CAST4_DEPARTURES,
  },

  // === Cast 4-bis: Variant (no missed cast) — skips Beat 1 ===
  {
    id: 'nereia_t2_c4bis',
    tier: AffectionTier.Curious,
    name: 'The Morning You Did Not Come',
    beats: [
      // Starts directly at Beat 2 then Beat 3
      CAST4_BEAT2,
      CAST4_BEAT3_SILENT,
    ],
    departures: CAST4_DEPARTURES,
  },
];
