// No template assets required for the initial game loop.
// Add TemplateAsset declarations here when templates are needed.

import { TextureAsset } from "meta/worlds";

// Pre-constructed TextureAsset map for each shape (static string literals required by linter)
export const SHAPE_TEXTURE_MAP: Record<string, TextureAsset> = {
  //circle:              new TextureAsset('@shape/circle.png'),
  circleGreen:         new TextureAsset('@shape/circleGreen.png'),

  //triangle:            new TextureAsset('@shape/triangle.png'),
  triangleBlue:        new TextureAsset('@shape/triangleBlue.png'),
  triangleBlue2:       new TextureAsset('@shape/triangleBlue2.png'),
  triangleCyan:        new TextureAsset('@shape/triangleCyan.png'),
  triangleGreen:       new TextureAsset('@shape/triangleGreen.png'),
  triangleOrange:      new TextureAsset('@shape/triangleOrange.png'),
  trianglePink:        new TextureAsset('@shape/trianglePink.png'),
  trianglePurple:      new TextureAsset('@shape/trianglePurple.png'),
  triangleRed:         new TextureAsset('@shape/triangleRed.png'),
  //triangleYellow:      new TextureAsset('@shape/triangleYellow.png'),

  //triangleEmpty:       new TextureAsset('@shape/triangleempty.png'),
  triangleEmptyBlue:   new TextureAsset('@shape/triangleemptyBlue.png'),
  triangleEmptyBlue2:  new TextureAsset('@shape/triangleemptyBlue2.png'),
  triangleEmptyCyan:   new TextureAsset('@shape/triangleemptyCyan.png'),
  triangleEmptyGreen:  new TextureAsset('@shape/triangleemptyGreen.png'),
  triangleEmptyOrange: new TextureAsset('@shape/triangleemptyOrange.png'),
  triangleEmptyPink:   new TextureAsset('@shape/triangleemptyPink.png'),
  triangleEmptyPurple: new TextureAsset('@shape/triangleemptyPurple.png'),
  triangleEmptyRed:    new TextureAsset('@shape/triangleemptyRed.png'),
  //triangleEmptyYellow: new TextureAsset('@shape/triangleemptyYellow.png'),

  //square:              new TextureAsset('@shape/square.png'),
  squareBlue:          new TextureAsset('@shape/squareBlue.png'),
  squareBlue2:         new TextureAsset('@shape/squareBlue2.png'),
  squareCyan:          new TextureAsset('@shape/squareCyan.png'),
  squareGreen:         new TextureAsset('@shape/squareGreen.png'),
  squareOrange:        new TextureAsset('@shape/squareOrange.png'),
  squarePink:          new TextureAsset('@shape/squarePink.png'),
  squarePurple:        new TextureAsset('@shape/squarePurple.png'),
  squareRed:           new TextureAsset('@shape/squareRed.png'),
  //squareYellow:        new TextureAsset('@shape/squareYellow.png'),

  //squareTilted:        new TextureAsset('@shape/squaretilted.png'),
  squareTiltedBlue:    new TextureAsset('@shape/squaretiltedBlue.png'),
  squareTiltedBlue2:   new TextureAsset('@shape/squaretiltedBlue2.png'),
  squareTiltedCyan:    new TextureAsset('@shape/squaretiltedCyan.png'),
  squareTiltedGreen:   new TextureAsset('@shape/squaretiltedGreen.png'),
  squareTiltedOrange:  new TextureAsset('@shape/squaretiltedOrange.png'),
  squareTiltedPink:    new TextureAsset('@shape/squaretiltedPink.png'),
  squareTiltedPurple:  new TextureAsset('@shape/squaretiltedPurple.png'),
  squareTiltedRed:     new TextureAsset('@shape/squaretiltedRed.png'),
  //squareTiltedYellow:  new TextureAsset('@shape/squaretiltedYellow.png'),

  //pentagon:            new TextureAsset('@shape/pentagon.png'),
  pentagonBlue:        new TextureAsset('@shape/pentagonBlue.png'),
  pentagonBlue2:       new TextureAsset('@shape/pentagonBlue2.png'),
  pentagonCyan:        new TextureAsset('@shape/pentagonCyan.png'),
  pentagonGreen:       new TextureAsset('@shape/pentagonGreen.png'),
  pentagonOrange:      new TextureAsset('@shape/pentagonOrange.png'),
  pentagonPink:        new TextureAsset('@shape/pentagonPink.png'),
  pentagonPurple:      new TextureAsset('@shape/pentagonPurple.png'),
  pentagonRed:         new TextureAsset('@shape/pentagonRed.png'),
  //pentagonYellow:      new TextureAsset('@shape/pentagonYellow.png'),

  //hexagon:             new TextureAsset('@shape/hexagon.png'),
  hexagonBlue:         new TextureAsset('@shape/hexagonBlue.png'),
  hexagonBlue2:        new TextureAsset('@shape/hexagonBlue2.png'),
  hexagonCyan:         new TextureAsset('@shape/hexagonCyan.png'),
  hexagonGreen:        new TextureAsset('@shape/hexagonGreen.png'),
  hexagonOrange:       new TextureAsset('@shape/hexagonOrange.png'),
  hexagonPink:         new TextureAsset('@shape/hexagonPink.png'),
  hexagonPurple:       new TextureAsset('@shape/hexagonPurple.png'),
  hexagonRed:          new TextureAsset('@shape/hexagonRed.png'),
  //hexagonYellow:       new TextureAsset('@shape/hexagonYellow.png'),

  //starEmpty:           new TextureAsset('@shape/starempty.png'),
  starEmptyBlue:       new TextureAsset('@shape/staremptyBlue.png'),
  starEmptyBlue2:      new TextureAsset('@shape/staremptyBlue2.png'),
  starEmptyCyan:       new TextureAsset('@shape/staremptyCyan.png'),
  starEmptyGreen:      new TextureAsset('@shape/staremptyGreen.png'),
  starEmptyOrange:     new TextureAsset('@shape/staremptyOrange.png'),
  starEmptyPink:       new TextureAsset('@shape/staremptyPink.png'),
  starEmptyPurple:     new TextureAsset('@shape/staremptyPurple.png'),
  starEmptyRed:        new TextureAsset('@shape/staremptyRed.png'),
  //starEmptyYellow:     new TextureAsset('@shape/staremptyYellow.png'),

  //starFill:            new TextureAsset('@shape/starfill.png'),
  starFillBlue:        new TextureAsset('@shape/starfillBlue.png'),
  starFillBlue2:       new TextureAsset('@shape/starfillBlue2.png'),
  starFillCyan:        new TextureAsset('@shape/starfillCyan.png'),
  starFillGreen:       new TextureAsset('@shape/starfillGreen.png'),
  starFillOrange:      new TextureAsset('@shape/starfillOrange.png'),
  starFillPink:        new TextureAsset('@shape/starfillPink.png'),
  starFillPurple:      new TextureAsset('@shape/starfillPurple.png'),
  starFillRed:         new TextureAsset('@shape/starfillRed.png'),
  //starFillYellow:      new TextureAsset('@shape/starfillYellow.png'),

  //heart:               new TextureAsset('@shape/heart.png'),
  heartBlue:           new TextureAsset('@shape/heartBlue.png'),
  heartBlue2:          new TextureAsset('@shape/heartBlue2.png'),
  heartCyan:           new TextureAsset('@shape/heartCyan.png'),
  heartGreen:          new TextureAsset('@shape/heartGreen.png'),
  heartOrange:         new TextureAsset('@shape/heartOrange.png'),
  heartPink:           new TextureAsset('@shape/heartPink.png'),
  heartPurple:         new TextureAsset('@shape/heartPurple.png'),  
  heartRed:            new TextureAsset('@shape/heartRed.png'),
  //heartYellow:         new TextureAsset('@shape/heartYellow.png'),

  //heartEmpty:          new TextureAsset('@shape/heartempty.png'),
  heartEmptyBlue:      new TextureAsset('@shape/heartemptyBlue.png'),
  heartEmptyBlue2:     new TextureAsset('@shape/heartemptyBlue2.png'),
  heartEmptyCyan:      new TextureAsset('@shape/heartemptyCyan.png'),
  heartEmptyGreen:     new TextureAsset('@shape/heartemptyGreen.png'),
  heartEmptyOrange:    new TextureAsset('@shape/heartemptyOrange.png'),
  heartEmptyPink:      new TextureAsset('@shape/heartemptyPink.png'),
  heartEmptyPurple:    new TextureAsset('@shape/heartemptyPurple.png'),
  heartEmptyRed:       new TextureAsset('@shape/heartemptyRed.png'),
  //heartEmptyYellow:    new TextureAsset('@shape/heartemptyYellow.png'),
};
