import { TextureAsset } from "meta/worlds";

export const SHAPE_TEXTURE_MAP: Record<string, TextureAsset> = {
  circleBlue:          new TextureAsset('@shape/circleBlue.png'),
  circleCyan:          new TextureAsset('@shape/circleCyan.png'),
  circleGreen:         new TextureAsset('@shape/circleGreen.png'),
  circleOrange:        new TextureAsset('@shape/circleOrange.png'),
  circlePink:          new TextureAsset('@shape/circlePink.png'),
  circlePurple:        new TextureAsset('@shape/circlepurple.png'),
  circleRed:           new TextureAsset('@shape/circleRed.png'),
  circleYellow:        new TextureAsset('@shape/circleYellow.png'),

  diamondBlue:         new TextureAsset('@shape/diamondBlue.png'),
  diamondCyan:         new TextureAsset('@shape/diamondCyan.png'),
  diamondGreen:        new TextureAsset('@shape/diamondGreen.png'),
  diamondOrange:       new TextureAsset('@shape/diamondOrange.png'),
  diamondPink:         new TextureAsset('@shape/diamondPink.png'),
  diamondPurple:       new TextureAsset('@shape/diamondPurple.png'),
  diamondRed:          new TextureAsset('@shape/diamondRed.png'),
  diamondYellow:       new TextureAsset('@shape/diamondYellow.png'),

  heartBlue:           new TextureAsset('@shape/heartBlue.png'),
  heartCyan:           new TextureAsset('@shape/heartCyan.png'),
  heartGreen:          new TextureAsset('@shape/heartGreen.png'),
  heartOrange:         new TextureAsset('@shape/heartOrange.png'),
  heartPink:           new TextureAsset('@shape/heartPink.png'),
  heartPurple:         new TextureAsset('@shape/heartPurple.png'),
  heartRed:            new TextureAsset('@shape/heartRed.png'),
  heartYellow:         new TextureAsset('@shape/heartYellow.png'),

  pentagonBlue:        new TextureAsset('@shape/pentagonBlue.png'),
  pentagonCyan:        new TextureAsset('@shape/pentagonCyan.png'),
  pentagonGreen:       new TextureAsset('@shape/pentagonGreen.png'),
  pentagonOrange:      new TextureAsset('@shape/pentagonOrange.png'),
  pentagonPink:        new TextureAsset('@shape/pentagonPink.png'),
  pentagonPurple:      new TextureAsset('@shape/pentagonPurple.png'),
  pentagonRed:         new TextureAsset('@shape/pentagonRed.png'),
  pentagonYellow:      new TextureAsset('@shape/pentagonYellow.png'),

  squareBlue:          new TextureAsset('@shape/squareBlue.png'),
  squareCyan:          new TextureAsset('@shape/squareCyan.png'),
  squareGreen:         new TextureAsset('@shape/squareGreen.png'),
  squareOrange:        new TextureAsset('@shape/squareOrange.png'),
  squarePink:          new TextureAsset('@shape/squarePink.png'),
  squarePurple:        new TextureAsset('@shape/squarePurple.png'),
  squareRed:           new TextureAsset('@shape/squareRed.png'),
  squareYellow:        new TextureAsset('@shape/squareYellow.png'),

  starFillBlue:        new TextureAsset('@shape/starfillBlue.png'),
  starFillCyan:        new TextureAsset('@shape/starfillCyan.png'),
  starFillGreen:       new TextureAsset('@shape/starfillGreen.png'),
  starFillOrange:      new TextureAsset('@shape/starfillOrange.png'),
  starFillPink:        new TextureAsset('@shape/starfillPink.png'),
  starFillPurple:      new TextureAsset('@shape/starfillPurple.png'),
  starFillRed:         new TextureAsset('@shape/starfillRed.png'),
  starFillYellow:      new TextureAsset('@shape/starfillYellow.png'),

  triangleBlue:        new TextureAsset('@shape/triangleBlue.png'),
  triangleCyan:        new TextureAsset('@shape/triangleCyan.png'),
  triangleGreen:       new TextureAsset('@shape/triangleGreen.png'),
  triangleOrange:      new TextureAsset('@shape/triangleOrange.png'),
  trianglePink:        new TextureAsset('@shape/trianglePink.png'),
  trianglePurple:      new TextureAsset('@shape/trianglePurple.png'),
  triangleRed:         new TextureAsset('@shape/triangleRed.png'),
  triangleYellow:      new TextureAsset('@shape/triangleYellow.png'),
};
